CREATE TABLE IF NOT EXISTS BbpsBillReminderLog (
  id INT NOT NULL AUTO_INCREMENT,
  dedupeKey VARCHAR(255) NOT NULL,
  rechargeId INT NULL,
  customerId VARCHAR(255) NULL,
  email VARCHAR(255) NULL,
  billerId VARCHAR(64) NULL,
  billerName VARCHAR(255) NULL,
  consumerNo VARCHAR(128) NULL,
  dueDate VARCHAR(32) NULL,
  eventType VARCHAR(64) NULL,
  emailStatus VARCHAR(32) NULL,
  message VARCHAR(1000) NULL,
  providerResponse VARCHAR(1000) NULL,
  verificationStatus VARCHAR(64) NULL,
  verificationClientTransactionId VARCHAR(128) NULL,
  verificationStartedAt BIGINT NULL,
  verificationCompletedAt BIGINT NULL,
  verificationAttempts INT NULL DEFAULT 0,
  liveCheckStatus VARCHAR(64) NULL,
  liveCheckReason VARCHAR(500) NULL,
  liveCheckDueDate VARCHAR(32) NULL,
  liveCheckAmount DECIMAL(18,2) NULL,
  liveCheckRawResponse TEXT NULL,
  reminderSkippedReason VARCHAR(255) NULL,
  createdAt BIGINT NULL,
  updatedAt BIGINT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_bbps_bill_reminder_log_dedupe_key (dedupeKey)
);
