com.dipcoin.api.config.ApplicationProperties.uiServingHostPort=https://stage.ostaapp.com
com.dipcoin.api.config.ApplicationProperties.verifySubuserUrl=/user/forgotpassword
com.dipcoin.api.config.ApplicationProperties.adminVerifySubuserUrl=/user/admin/forgotpassword
com.dipcoin.api.config.ApplicationProperties.uploadFileToS3=true
com.dipcoin.api.config.ApplicationProperties.logoImgPath=/imgs/home-page/logo-purp.png
com.dipcoin.api.config.ApplicationProperties.mailImgPath=/imgs/mail.png
com.dipcoin.api.config.ApplicationProperties.oauth2EncryptionKey=superrandomstring
com.dipcoin.api.config.ApplicationProperties.ostaRedirectUrl=https://stage.ostaapp.com/ostaGateway
com.dipcoin.api.config.ApplicationProperties.deleteWallet=true
com.dipcoin.api.config.ApplicationProperties.offlineApi.job=http://43.205.59.83:8080/offline/schedule/job
com.dipcoin.api.config.ApplicationProperties.offlineApi.uploadFile=http://43.205.59.83:8080/offline/schedule/uploadFile
com.dipcoin.api.config.ApplicationProperties.sdkRedirectUrl=https://stage.ostaapp.com:8448/user/register/tnc
com.dipcoin.api.config.ApplicationProperties.webUrl=https://stage.ostaapp.com:8448/user/login
com.dipcoin.api.config.ApplicationProperties.appUrl=https://play.google.com/store/apps/details?id=com.osta.customer
com.dipcoin.api.config.ApplicationProperties.localPath=/home/ostau/
com.dipcoin.api.config.ApplicationProperties.senderEmail=alerts-donotreply@ostaapp.com
com.dipcoin.api.config.ApplicationProperties.webUrl.otp=https://stage.ostaapp.com:8448/user/register/verify/otp
com.dipcoin.api.config.ApplicationProperties.sendBulkTollTagDeletionStatusSheetMailTo=sophia@ostaapp.com,ashish@ostaapp.com
com.dipcoin.api.config.ApplicationProperties.fraudMgmt=false
com.dipcoin.api.config.ApplicationProperties.awsSMSClient=false
com.dipcoin.api.config.ApplicationProperties.runAudit=true

com.dipcoin.commons.SesEmailClient.sesRegion=us-east-1
com.dipcoin.commons.email.restricted.domain=@contact.ostaapp.com,@co.in
com.dipcoin.commons.CommonsProperties.smsClient.connect=false
com.dipcoin.commons.CommonsProperties.emailClient.connect=true

spring.datasource.url=jdbc:mysql://stage-db-new.cf2ik20ms4wt.ap-south-1.rds.amazonaws.com:3306/dipcoin?allowMultiQueries=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
spring.datasource.username=dipcoindb
spring.datasource.password=O5taD1pC0in
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
