# ================= FINACUS BBPS API INTEGRATION =================

finacus.biller.categories.url=https://nmmobbbpstjsb.finacuspayments.com:8089/PublicService/AgentBankingAPI/FinBbpsABService.asmx/GetBillerCategories
finacus.biller.coverages.url=https://nmmobbbpstjsb.finacuspayments.com:8089/PublicService/AgentBankingAPI/FinBbpsABService.asmx/GetBillerCoverages
finacus.biller.by.categories.url=https://nmmobbbpstjsb.finacuspayments.com:8089/PublicService/AgentBankingAPI/FinBbpsABService.asmx/GetBillersByCategory
finacus.get.customer.params.url=https://nmmobbbpstjsb.finacuspayments.com:8089/PublicService/AgentBankingAPI/FinBbpsABService.asmx/GetCustomerParamsByBillerId
finacus.get.bill.payment.url=https://nmmobbbpstjsb.finacuspayments.com:8089/PublicService/AgentBankingAPI/FinBbpsABService.asmx
finacus.get.plan.url=https://nmmobbbpstjsb.finacuspayments.com:8089/PublicService/AgentBankingAPI/FinBbpsABService.asmx/GetPlanMDMList
finacus.get.plan.description.url=https://nmmobbbpstjsb.finacuspayments.com:8089/PublicService/AgentBankingAPI/FinBbpsABService.asmx/GetPlanDescriptionbyBillerId
finacus.get.params.url=https://nmmobbbpstjsb.finacuspayments.com:8089/PublicService/AgentBankingAPI/FinBbpsABService.asmx/GetCustomerParamsByBillerId
finacus.get.zone.url=https://nmmobbbpstjsb.finacuspayments.com:8089/PublicService/AgentBankingAPI/FinBbpsABService.asmx/GetZoneByBillerId

bbps.api.checksum-key=BBPS@TJSBPROD
bbps.api.base-url=https://nmmobbbpstjsb.finacuspayments.com:8089/PublicService/AgentBankingAPI/FinBbpsABService.asmx

finacus.complaint.url=https://nmmobbbpstjsb.finacuspayments.com:8089/PublicService/AgentBankingAPI/FinBbpsABService.asmx
finacus.complaint.soapaction="http://tempuri.org/RegisterTxnComplaintRequest"
finacus.agent.id=TJ01TB67INBBAR777208
finacus.init.channel=INTB
finacus.request.mobile-number=9561151538
finacus.request.ip-address=172.20.2.30
finacus.request.mac-address=C8-1F-66-02-69-C0
finacus.plan.url=https://nmmobbbpstjsb.finacuspayments.com:8089/PublicService/AgentBankingAPI/FinBbpsABService.asmx/GetPlanMDMList
finacus.payment.channel=AGT
finacus.payment.mode=Wallet
finacus.payment.mti=PAYMENT
finacus.complaint.status.soapaction="http://tempuri.org/SendComplaintStatusRequest"
finacus.raise.ticket.soapaction="http://tempuri.org/BbpsRaiseTicket"
finacus.ticket.status.soapaction="http://tempuri.org/BbpsTicketStatus"
finacus.get.tickets.history.soapaction="http://tempuri.org/BbpsGetTicketsHistory"
