####################### PAYMENT GATEWAY PROPERTIES #####################

com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.paytmMerchantId=chuZON47688322129877
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.paytmMerchantKey=7iD4cYu9U5rFZI2Z
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.paytmRefundUrl=https://securegw.paytm.in/refund/apply
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.paytmTransactionStatusUrl=https://securegw.paytm.in/order/status
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.paytmRefundStatusUrl=https://securegw.paytm.in/v2/refund/status

com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.ostaOauthUrl=https://api.ostaapp.com/api/v1/oauth2/token
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.ostaAddMoneyUrl=https://api.ostaapp.com/api/v1/oauth2/addMoney/user

com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.paypalClientId=AS6Rxfon1oULw5dpERLycjHuuiOcCjeb3536qFJ9IyjVr4QdyRFXKgzhA2zLkZjIzFJqvHOuQG9vMQ4m
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.paypalSecret=EI24rVaHiK7a2uRAV0pvi1BvSXLVPdjVc1j99GHxYSy3MmPILokm03DmZTjD3Nis-sN4jcmf4PIeMh4y
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.paypalGetOauthTokenUrl=https://api.paypal.com/v1/oauth2/token
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.paypalCreateOrderReq=https://api.paypal.com/v2/checkout/orders
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.paypalSTCPutReq=https://api.paypal.com/v1/risk/transaction-contexts/6Z9AEGM7EPP8Q/trackingId
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.paypalTransactionStatusUrl=https://api.paypal.com/v2/checkout/orders/

com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.isProxyEnabled=true
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.port=3128
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.ip=cedge.proxy.in

com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.getTxnStatusUrl=https://apiprod.ostaapp.com/api/v1/oauth2/transactions/status
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.internalCapturedPgStatusUrl=https://apiprod.ostaapp.com/api/v1/jwt/bbpsPartner/customer/partner/pg/captured-status
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.internalAggrepayPaymentStatusUrl=https://apiprod.ostaapp.com/api/v1/jwt/bbpsPartner/customer/agreePay/statusCheck
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.internalAggrepayRefundUrl=https://apiprod.ostaapp.com/api/v1/jwt/bbpsPartner/customer/agreePay/refund
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.internalAggrepayRefundStatusUrl=https://apiprod.ostaapp.com/api/v1/jwt/bbpsPartner/customer/partner/aggrepay/refund-status
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.bankCallBackUrl=https://api.ostaapp.com/api/v1/oauth2/customer/bank/callBackUrl
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.partnerRefundInitiate=https://api.ostaapp.com/api/v1/merchant/refund

com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.aggrepayPaymentSeamlessUrl=https://biz.aggrepaypayments.com/v2/paymentseamlessrequest
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.aggrepayCheckTransactionStatusUrl=https://biz.aggrepaypayments.com/v2/paymentstatus
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.aggrepayRefundUrl=https://biz.aggrepaypayments.com/v2/refundrequest
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.aggrepayGenerateAccessTokenUrl=https://biz.aggrepaypayments.com/v2/generateaccesstoken
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.aggrepaySaveCardDetailsUrl=https://biz.aggrepaypayments.com/v2/savecarddetails
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.aggrepayGetSavedCardSessionTokensUrl=https://biz.aggrepaypayments.com/v2/getsavedcardsessiontokens
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.aggrepayPaymentSavedCardRequestUrl=https://biz.aggrepaypayments.com/v2/paymentsavedcardrequest
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.aggrepaySettlementdetailsRequestUrl=https://biz.aggrepaypayments.com/v2/getsettlementdetails

com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.confirmPaymentRequestUrl=https://b2b.algorhythms.in:8000/confirmPaymentRequest/
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.primeFlixUrl=https://devapi.primeflix.app/payment_status_update
